<!DOCTYPE html>
<head>
	<title>Profile</title>
	<link rel="stylesheet" href="css/style.css">
</head>

<body>
	<?php include 'nav.php'?>
<div id="wrapper">
		<div id="box3">
		<img class = 'imgthree' src="images/prof.jpg" alt="DefaultProf">
		<h3>EXPERIENCES</h3>
		<h4> - Layout Artist for CET Foglio de Tigris</h4>
		<h4> - Layout Artist and Writer for St. Benilde's Publication</h4>
		<h4> - Networks Coordinator and Chapter Convener of 1Sambayan Lasalyano</h4>
		</div>
		<div id="box4">
		<h5>PROFILE</h5>
		<p></p>
		<p>Full Name: Isaac Cris Nicoli D. Sabandal</p>
		<p>Age: 19</p>
		<p>Status: College Freshman</p>
		<p>Major: Information Technology</p>
		<p>Address: Bacolod City</p>
		<p>Origin: Metro Manila</p>
		<p>Nationality: Filipino</p>
		</div>
	</div>

		<script src="script/script.js"></script>
</body>